### ISSUE TITLE
Are you open to contributions?

### ISSUE THREAD

**Issue by borisyordanov** [rebassjs/rebassjs.org#8]
I made a small update on the docs which i'd like to share with you. Can you add me as a contributor so i can make a branch for my updates and open a pull request?

**Comment by borisyordanov** [comment]
I wanted to make a new branch (which i wasn't allowed to do) and then make the PR. Should i just use one of the existing branches(if yes, please specify which branch you'd prefer)?

**Comment by jxnblk** [comment]
You can fork this repo, make changes, then submit a pull request back to this repo. This is how GitHub works, so want to make sure you understand the workflow

**Comment by jxnblk** [comment]
Sorry, I linked to the wrong documentation above, see: https://help.github.com/articles/creating-a-pull-request-from-a-fork/
